# Generated by Django 5.1.3 on 2024-11-30 09:50

import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('is_visible', models.BooleanField(default=True, help_text='Снимите галочку, что бы убрать из поиска', verbose_name='В зоне видимости')),
                ('description', models.TextField(default='Описание отсутствует', verbose_name='Описание')),
                ('image', models.ImageField(null=True, upload_to=product.models.directory_path, verbose_name='Изображение')),
                ('slug', models.SlugField(help_text='Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.', unique=True, verbose_name='Идентификатор')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_category')],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('is_visible', models.BooleanField(default=True, help_text='Снимите галочку, что бы убрать из поиска', verbose_name='В зоне видимости')),
                ('slug', models.SlugField(help_text='Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.', unique=True, verbose_name='Идентификатор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='product.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'под категория',
                'verbose_name_plural': 'Под категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('is_visible', models.BooleanField(default=True, help_text='Снимите галочку, что бы убрать из поиска', verbose_name='В зоне видимости')),
                ('description', models.TextField(default='Описание отсутствует', verbose_name='Описание')),
                ('image', models.ImageField(null=True, upload_to=product.models.directory_path, verbose_name='Изображение')),
                ('params', models.JSONField(verbose_name='Параметры')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('in_stock', models.BooleanField(default=False, verbose_name='В наличии')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='product.subcategory', verbose_name='Под категория')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_subcategory'),
        ),
    ]
